const gimages=[
    {
      imlink:'https://ik.imagekit.io/thestylist/valaya/pub/media_valaya/HOMEPAGE_IMAGES/14_Apr_22/shoot1.jpg',
      category:'shoots',
      id:1
    },
    {
      imlink:'https://ik.imagekit.io/thestylist/valaya/pub/media_valaya/HOMEPAGE_IMAGES/14_Apr_22/shoot2.jpg',
      category:'shoots',
      id:2
    },
    {
      imlink:'https://ik.imagekit.io/thestylist/valaya/pub/media_valaya/HOMEPAGE_IMAGES/20_Apr_22/shoot3.jpg',
      category:'shoots',
      id:3
    },
    {
      imlink:'https://ik.imagekit.io/thestylist/valaya/pub/media_valaya/HOMEPAGE_IMAGES/22_Apr_22/media2.jpg',
      category:'press&media',
      id:4
    },
    {
      imlink:'https://ik.imagekit.io/thestylist/valaya/pub/media_valaya/HOMEPAGE_IMAGES/22_Apr_22/media1.jpg',
      category:'press&media',
      id:5
    },
    {
      imlink:'https://ik.imagekit.io/thestylist/valaya/pub/media_valaya/HOMEPAGE_IMAGES/22_Apr_22/media2.jpg',
      category:'press&media',
      id:6
    },
    {
      imlink:'https://ik.imagekit.io/thestylist/valaya/pub/media_valaya/HOMEPAGE_IMAGES/22_Apr_22/runway2.jpg',
      category:'runaway',
      id:7
    },
    {
      imlink:'https://ik.imagekit.io/thestylist/valaya/pub/media_valaya/HOMEPAGE_IMAGES/22_Apr_22/runway2.jpg',
      category:'runaway',
      id:8
    },
    {
      imlink:'https://ik.imagekit.io/thestylist/valaya/pub/media_valaya/HOMEPAGE_IMAGES/22_Apr_22/runway2.jpg',
      category:'runaway',
      id:9
    },
    {
      imlink:'https://ik.imagekit.io/thestylist/valaya/pub/media_valaya/HOMEPAGE_IMAGES/22_Apr_22/celeb1.jpg',
      category:'celebs',
      id:10
    },
    {
      imlink:'https://ik.imagekit.io/thestylist/valaya/pub/media_valaya/HOMEPAGE_IMAGES/22_Apr_22/celeb2.jpg',
      category:'celebs',
      id:11
    },
    {
      imlink:'https://ik.imagekit.io/thestylist/valaya/pub/media_valaya/HOMEPAGE_IMAGES/22_Apr_22/celeb3.jpg',
      category:'celebs',
      id:12
    },
]
export default gimages